
image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64
  - curl -o- -L https://yarnpkg.com/install.sh | TERM=xterm bash
  - yarn install

build_script:
  - yarn run dist
  - npm run pack-depl

test: off